import { existsSync } from 'node:fs';
import { mkdir, readdir, rm, rmdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import type { GuriPaths } from '../types';

export const GENERATED_HEADER = '// Generated by guri sync. Do not edit.';

export function slash(path: string): string {
    return path.split(sep).join('/');
}

export function importPath(fromFile: string, toFile: string): string {
    let path = slash(relative(dirname(fromFile), toFile)).replace(/\.d\.ts$/, '');
    if (!path.startsWith('.')) {
        path = `./${path}`;
    }
    return path;
}

export function relativeConfigPath(fromDir: string, toPath: string): string {
    let path = slash(relative(fromDir, toPath));
    if (!path.startsWith('.')) {
        path = `./${path}`;
    }
    return path;
}

/** A relative ESM module specifier from `fromDir` to a source file (extension stripped). */
export function moduleSpecifier(fromDir: string, target: string): string {
    let path = slash(relative(fromDir, target)).replace(/\.(?:[cm]?[jt]sx?)$/, '');
    if (!path.startsWith('.')) {
        path = `./${path}`;
    }
    return path;
}

export function typeFilePath(paths: GuriPaths, routeDir: string): string {
    // Mirror the folder's source directory (relative to the project root) under
    // `<outDir>/types/`. Combined with `rootDirs: ["..", "./types"]`, this lets a file's
    const sourceDir = relative(paths.cwd, routeDir);
    return join(paths.outDir, 'types', sourceDir, '$types.d.ts');
}

export function assertSafeOutDir(paths: GuriPaths): void {
    const rel = relative(paths.cwd, paths.outDir);
    if (!rel || rel.startsWith('..') || rel.includes(`..${sep}`)) {
        throw new Error(`Refusing to sync outside the project root: ${paths.outDir}`);
    }
}

const writeCache = new Map<string, string>();

/** Write a generated file, skipping the write when its content is unchanged and still on disk. */
export async function writeGenerated(path: string, content: string): Promise<void> {
    if (writeCache.get(path) === content && existsSync(path)) {
        return;
    }
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
    writeCache.set(path, content);
}

export async function writeJson(path: string, value: unknown): Promise<void> {
    await writeGenerated(path, `${JSON.stringify(value, null, 2)}\n`);
}

/**
 * Remove generated files no longer in `keep`, plus any directories left empty. Lets sync
 * overwrite in place (no upfront wipe), so the editor never sees `tsconfig`/`$types`
 * disappear during a slow regeneration.
 */
export async function pruneDir(dir: string, keep: Set<string>): Promise<void> {
    let entries;
    try {
        entries = await readdir(dir, { withFileTypes: true });
    } catch {
        return;
    }
    for (const entry of entries) {
        const full = join(dir, entry.name);
        if (entry.isDirectory()) {
            await pruneDir(full, keep);
            await rmdir(full).catch(() => {}); // succeeds only if now empty
        } else if (!keep.has(full)) {
            await rm(full, { force: true });
            writeCache.delete(full); // a recreated file with identical content must write again
        }
    }
}
